@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": ""
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": false,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": false,
    "cutConstructors": false
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false // root node is included
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.codecool.mi6.services.AlertService"
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_867524938 { 
   	label=codecool
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1407640290 { 
   	label=mi6
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   AlertService1250869565[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)AlertService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ raiseSecurityAlert(cause: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

ConsoleAlertService1250869565[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ConsoleAlertService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ raiseSecurityAlert(cause: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

LoginService1250869565[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)LoginService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   alertService: AlertService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   credentials: CredentialStore [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   md5: DigestUtils [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ LoginService(credentials: CredentialStore, alertService: AlertService)</TD></TR>
<TR><TD ALIGN="LEFT" >- hashPassword(password: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ login(userName: String, password: String): Credential</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MissionService1250869565[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MissionService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   alertService: AlertService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   missionStore: MissionStore [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ MissionService(missionStore: MissionStore, alertService: AlertService)</TD></TR>
<TR><TD ALIGN="LEFT" >+ addMission(c: Credential, m: Mission)</TD></TR>
<TR><TD ALIGN="LEFT" >+ deactivate(c: Credential, title: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ findActiveMissions(credential: Credential): List&lt;Mission&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
AlertService1250869565 -> ConsoleAlertService1250869565[arrowhead=none, arrowtail=empty, dir=both];
LoginService1250869565 -> AlertService1250869565[label="alertService
[0..1]"];
MissionService1250869565 -> AlertService1250869565[label="alertService
[0..1]"];
    
}
@enduml