@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": ""
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": false,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": false,
    "cutConstructors": false
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false // root node is included
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.codecool.mi6.services.MissionService"
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_867524938 { 
   	label=codecool
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1407640290 { 
   	label=mi6
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   App1939028433[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)App</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   loginService: LoginService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   missionService: MissionService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   scanner: Scanner [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ App(scanner: Scanner)</TD></TR>
<TR><TD ALIGN="LEFT" >- listMissions(credential: Credential)</TD></TR>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
<TR><TD ALIGN="LEFT" >- promptForLogin(): Credential</TD></TR>
<TR><TD ALIGN="LEFT" >- promptForMissionToDeactivate(credential: Credential)</TD></TR>
<TR><TD ALIGN="LEFT" >- promptForNewMissionToAdd(credential: Credential)</TD></TR>
<TR><TD ALIGN="LEFT" >- promptMenuChoice(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ start()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ConsoleAlertService1250869565[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ConsoleAlertService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ raiseSecurityAlert(cause: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

InMemoryMissionStore1767014481[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)InMemoryMissionStore</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   missions: List&lt;Mission&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ InMemoryMissionStore()</TD></TR>
<TR><TD ALIGN="LEFT" >+ findActive(level: SecurityLevel): List&lt;Mission&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findByTitle(title: String): Mission</TD></TR>
<TR><TD ALIGN="LEFT" >+ save(m: Mission)</TD></TR>
<TR><TD ALIGN="LEFT" >+ update(m: Mission)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Mission1590281993[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Mission</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   access: SecurityLevel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   active: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   deadLine: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   description: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   targetName: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   title: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ Mission(title: String, active: boolean, targetName: String, access: SecurityLevel, description: String, deadLine: LocalDate)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAccess(): SecurityLevel</TD></TR>
<TR><TD ALIGN="LEFT" >+ getDeadLine(): LocalDate</TD></TR>
<TR><TD ALIGN="LEFT" >+ getDescription(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ getTargetName(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ getTitle(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ isActive(): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ setAccess(access: SecurityLevel)</TD></TR>
<TR><TD ALIGN="LEFT" >+ setActive(active: boolean)</TD></TR>
<TR><TD ALIGN="LEFT" >+ setDeadLine(deadLine: LocalDate)</TD></TR>
<TR><TD ALIGN="LEFT" >+ setDescription(description: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ setTargetName(targetName: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ setTitle(title: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MissionService1250869565[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MissionService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   alertService: AlertService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   missionStore: MissionStore [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ MissionService(missionStore: MissionStore, alertService: AlertService)</TD></TR>
<TR><TD ALIGN="LEFT" >+ addMission(c: Credential, m: Mission)</TD></TR>
<TR><TD ALIGN="LEFT" >+ deactivate(c: Credential, title: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ findActiveMissions(credential: Credential): List&lt;Mission&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SecurityLevel1590281993[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(E)SecurityLevel</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   INVALID: SecurityLevel [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   ONE: SecurityLevel [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   THREE: SecurityLevel [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   TWO: SecurityLevel [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ valueOf(name: String): SecurityLevel</TD></TR>
<TR><TD ALIGN="LEFT" >+ values(): SecurityLevel[]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#DCFBD5"
];
} 
} 

'edges    
App1939028433 -> MissionService1250869565[label="missionService
[0..1]"];
InMemoryMissionStore1767014481 -> Mission1590281993[label="missions
[0..*]"];
Mission1590281993 -> SecurityLevel1590281993[label="access
[0..1]"];
MissionService1250869565 -> ConsoleAlertService1250869565[arrowhead=none, arrowtail=empty, dir=both];
MissionService1250869565 -> InMemoryMissionStore1767014481[arrowhead=none, arrowtail=empty, dir=both];
    
}
@enduml